// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsjgeojmnfrxdenqcnge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzamdlb2ptbmZyeGRlbnFjbmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjQ2NjksImV4cCI6MjA2MDA0MDY2OX0.hGVOpYoURbyFWm1I7_y5_GqdrwknRS5psKbyPi4w-Lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);